import React, { useState } from 'react';
import './HeatmapViewer.css';

const HeatmapViewer = ({ originalImage, heatmapImage }) => {
  const [opacity, setOpacity] = useState(0.5);
  const [showHeatmap, setShowHeatmap] = useState(true);

  if (!originalImage) return null;

  return (
    <div className="heatmap-container">
      <div className="heatmap-header">
        <h3>AI Explainability (Grad-CAM)</h3>
        <p className="heatmap-desc">
          The red areas highlight the regions of the tissue the Deep Learning model focused on to make its prediction.
        </p>
      </div>

      <div className="visualization-area">
        <div className="image-stack">
          {/* Base Layer: Original CT Scan */}
          <img 
            src={originalImage} 
            alt="Original CT Scan" 
            className="base-scan" 
          />
          
          {/* Top Layer: The Grad-CAM Heatmap overlay */}
          {heatmapImage && showHeatmap && (
            <img 
              src={heatmapImage} 
              alt="Model Attention Heatmap" 
              className="heatmap-overlay"
              style={{ opacity: opacity }}
            />
          )}

          {!heatmapImage && (
            <div className="no-heatmap-fallback">
              <p>Heatmap data not generated by backend for this scan.</p>
            </div>
          )}
        </div>

        {heatmapImage && (
          <div className="controls-panel">
            <div className="control-group">
              <label htmlFor="heatmap-toggle" className="toggle-label">
                <span>View Overlay</span>
                <label className="switch">
                  <input 
                    type="checkbox" 
                    id="heatmap-toggle"
                    checked={showHeatmap}
                    onChange={(e) => setShowHeatmap(e.target.checked)}
                  />
                  <span className="slider round"></span>
                </label>
              </label>
            </div>

            <div className={`control-group ${!showHeatmap ? 'disabled' : ''}`}>
              <label htmlFor="opacity-slider">Focus Intensity (Opacity)</label>
              <input 
                type="range" 
                id="opacity-slider"
                min="0.1" 
                max="1.0" 
                step="0.05" 
                value={opacity} 
                onChange={(e) => setOpacity(parseFloat(e.target.value))}
                disabled={!showHeatmap}
                className="range-slider"
              />
              <div className="range-labels">
                <span>Low</span>
                <span>High</span>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default HeatmapViewer;
